#!/usr/bin/env bash
# Script to do inference and evaluation of rpg_event_representation_learning

root_path=$POLED_PATH

# Parse YAML function
source "$root_path"/scripts/parse_yaml.sh

# Parse the master YAML file
eval $(parse_yaml "$root_path"/config/master.yaml)
# Parse datasets paths YAML file (datasets)
datasets_yaml="$common_root"/"$common_cfg_root"/"$common_cfg_datasets"/"$datasets_cfg_file"
eval $(parse_yaml "$datasets_yaml")
# Parse the OLED YAML file (oled)
oled_yaml="$common_root"/"$common_cfg_root"/"$common_cfg_sampling"/"$oled_cfg_file"
eval $(parse_yaml "$oled_yaml")
# Parse RVT YAML file (method)
method_yaml="$common_root"/"$common_cfg_root"/"$common_cfg_methods"/"$rvt_cfg_file"
eval $(parse_yaml "$method_yaml")

# From OLED
for exp_cfg in "${oled_exp_cfgs[@]}"; do
  # Get experiment ID from the config file
  exp_yaml="$common_root"/"$common_cfg_root"/"$common_cfg_sampling"/"$exp_cfg"
  eval $(parse_yaml "$exp_yaml")
  exp_name="$sampler_params_exp_name"
  # From METHOD
  for dataset_name in "${method_datasets_name[@]}"; do
    var_dataset_root="$dataset_name"_root  # Get the variable Name (e.g. N-Caltech101_root, hsergb_root, ...)
    dataset_root="${!var_dataset_root}"  # Get the value of the variable generated by datasets_paths.yaml
    # TODO: Specifiy split (testing...)
    dataset_sys_path="$datasets_common_root"/"$dataset_root"  # Path to the dataset in the system
    dataset_docker_path="$method_docker_datasets"/"$dataset_root"  # Path to the dataset within the docker container
    # From OLED
    for sampler in "${oled_samplers[@]}"; do
      # From OLED
      for run in "${oled_runs[@]}"; do
        # From OLED
        for prob_init in "${oled_prob_inits[@]}"; do
          # Evaluate the downsampled events per method
          if [[ "$prob_init" == "10" ]]; then
            prob_init_dec=1
          else
            prob_init_dec="0."$prob_init
          fi
          run_descriptor="$sampler"_"$prob_init_dec"-"$run"
          
          echo "Running experiments for" "$run_descriptor", "experiment:" "$exp_name"

          # LOGS
          logs_sys_path="$common_root"/"$common_logs_path"/"$dataset_name"/"$method_name"/"$exp_name"/"$run_descriptor"
          logs_docker_path="$method_docker_app"/"$common_logs_path"/"$dataset_name"/"$method_name"/"$exp_name"/"$run_descriptor"
          mkdir -p "$logs_sys_path"
          chmod 777 "$logs_sys_path"
          logs_docker_res="$logs_docker_path"/"$common_logs_res_file"
          logs_res="$logs_sys_path"/"$common_logs_res_file"
          logs_size="$logs_sys_path"/"$common_logs_size_file"
          logs_time="$logs_sys_path"/"$common_logs_time_file"  
          logs_preproc_time="$logs_sys_path"/"$common_logs_preproc_time_file"

          # TODO: Specify this "sampling" or "original" in YAML files
          data_sys_path="$dataset_sys_path"/sampling/"$exp_name"/events_"$run_descriptor"
          data_docker_path="$dataset_docker_path"/sampling/"$exp_name"/events_"$run_descriptor"
          data_preproc_sys_path="$dataset_sys_path"/sampling/"$exp_name"/preproc_"$run_descriptor"
          data_preproc_docker_path="$dataset_docker_path"/sampling/"$exp_name"/preproc_"$run_descriptor"

          # PREPROCESS
          echo "Preprocessing events..."
          # Make necessary dirs
          docker exec -it "$method_docker_id" mkdir -p "$data_docker_path"/train
          docker exec -it "$method_docker_id" mkdir -p "$data_docker_path"/val
          docker exec -it "$method_docker_id" mkdir -p "$data_docker_path"/test

          start_time=$(date +%s)
          docker exec -it "$method_docker_id" \
            env PYTHONPATH="$method_docker_app":"$PYTHONPATH" \
            python "$method_docker_app"/"$method_genx_path"/"$method_preprocess" "$data_docker_path" "$data_preproc_docker_path" \
            "$method_genx_path"/conf_preprocess/representation/stacked_hist.yaml "$method_genx_path"/conf_preprocess/extraction/const_duration.yaml "$method_genx_path"/conf_preprocess/filter_gen1.yaml \
            -ds "$dataset_name" -np "$method_num_workers"
          end_time=$(date +%s)
          echo time: "$((end_time-start_time))" > "$logs_preproc_time"

          # EVALUATE
          echo "Running RVT, Saving logs to: $logs_res..."
          start_time=$(date +%s)
          docker exec -it "$method_docker_id" \
            bash -c "mkdir -p '$logs_docker_path'"

          docker exec -it "$method_docker_id" \
            env PYTHONPATH="$method_docker_app":"$PYTHONPATH" \
            python "$method_run" dataset="$dataset_name" dataset.path="$data_preproc_docker_path" checkpoint="$method_model_path"/"$method_checkpoint" \
            use_test_set=1 hardware.gpus="$method_gpu_id" +experiment/"$dataset_name"=base.yaml batch_size.eval=${method_batch_size} \
            model.postprocess.confidence_threshold=0.001 \
            eval_logs_path=${logs_docker_res}
          end_time=$(date +%s)

          # Copy local logs to system logs
          docker cp "$method_docker_id":${logs_docker_res} ${logs_res}

          echo time: "$((end_time-start_time))" > "$logs_time"
          echo "$data_sys_path"
          echo size: "$(du -sh "$data_sys_path")" > "$logs_size"

        done
      done
    done
  done
done
