#!/usr/bin/env bash
# Script to do inference and evaluation of rpg_event_representation_learning

root_path=$POLED_PATH

# Parse YAML function
source "$root_path"/scripts/parse_yaml.sh

# Parse the master YAML file
eval $(parse_yaml "$root_path"/config/master.yaml)
# Parse datasets paths YAML file (datasets)
datasets_yaml="$common_root"/"$common_cfg_root"/"$common_cfg_datasets"/"$datasets_cfg_file"
eval $(parse_yaml "$datasets_yaml")
# Parse the POLED YAML file (poled)
poled_yaml="$common_root"/"$common_cfg_root"/"$common_cfg_sampling"/"$poled_cfg_file"
eval $(parse_yaml "$poled_yaml")
# Parse RVT YAML file (method)
method_yaml="$common_root"/"$common_cfg_root"/"$common_cfg_methods"/"$esfp_cfg_file"
eval $(parse_yaml "$method_yaml")

# From POLED
for exp_cfg in "${poled_exp_cfgs[@]}"; do
  # Get experiment ID from the config file
  exp_yaml="$common_root"/"$common_cfg_root"/"$common_cfg_sampling"/"$exp_cfg"
  eval $(parse_yaml "$exp_yaml")
  exp_name="$sampler_params_exp_name"
  # From METHOD
  for dataset_name in "${method_datasets_name[@]}"; do
    var_dataset_root="$dataset_name"_root  # Get the variable Name (e.g. N-Caltech101_root, hsergb_root, ...)
    dataset_root="${!var_dataset_root}"  # Get the value of the variable generated by datasets_paths.yaml
    # TODO: Specifiy split (testing...)
    dataset_sys_path="$datasets_common_root"/"$dataset_root"  # Path to the dataset in the system
    dataset_docker_path="$method_docker_datasets"/"$dataset_root"  # Path to the dataset within the docker container
    # From POLED
    for sampler in "${poled_samplers[@]}"; do
      # From POLED
      for run in "${poled_runs[@]}"; do
        # From POLED
        for prob_init in "${poled_prob_inits[@]}"; do
          # Evaluate the downsampled events per method
          if [[ "$prob_init" == "10" ]]; then
            prob_init_dec=1
          else
            prob_init_dec="0."$prob_init
          fi
          run_descriptor="$sampler"_"$prob_init_dec"-"$run"
          
          echo "Running experiments for" "$run_descriptor", "experiment:" "$exp_name"

          # LOGS
          logs_sys_path="$common_root"/"$common_logs_path"/"$dataset_name"/"$method_name"/"$exp_name"/"$run_descriptor"/"$common_logs_retrained_path"
          logs_docker_path="$method_docker_app"/"$common_logs_path"/"$dataset_name"/"$method_name"/"$exp_name"/"$run_descriptor"/"$common_logs_retrained_path"
          mkdir -p "$logs_sys_path"
          chmod 777 "$logs_sys_path"
          logs_docker_res="$logs_docker_path"/"$common_logs_res_file"
          logs_res="$logs_sys_path"/"$common_logs_res_file"
          logs_size="$logs_sys_path"/"$common_logs_size_file"
          logs_time="$logs_sys_path"/"$common_logs_time_file"  

          # TODO: Specify this "sampling" or "original" in YAML files
          data_sys_path="$dataset_sys_path"/sampling/"$exp_name"/events_"$run_descriptor"
          data_docker_path="$dataset_docker_path"/sampling/"$exp_name"/events_"$run_descriptor"
          data_eval_sys_path="$data_sys_path"/test
          data_eval_docker_path="$data_docker_path"/test

          # EVALUATE
          echo "Running ESFP, Saving logs to: $logs_res..."
          start_time=$(date +%s)
          docker exec -it "$method_docker_id" \
            bash -c "mkdir -p '$logs_docker_path'"

          # Physics-based
          #docker exec -it "$method_docker_id" \
          #  env PYTHONPATH="$method_docker_app":"$PYTHONPATH" \
          #  python "$method_run" -path_dir "$data_eval_docker_path" -exp_name "results" -result_dir "$logs_docker_path"

          # Learning-based
          docker exec -it "$method_docker_id" \
            env PYTHONPATH="$method_docker_app":"$PYTHONPATH" \
            python "$method_train" --dataset realevents --dataroot "$data_docker_path" --netinput events_8_bins_cvgri --batch_size 4 \
                                   --exp_name "$exp_name"/"$run_descriptor" --logs_oled "$logs_docker_res" --training_mode all

          # Test
          docker exec -it "$method_docker_id" \
            env PYTHONPATH="$method_docker_app":"$PYTHONPATH" \
            python "$method_train" --dataset realevents --dataroot "$data_docker_path" --netinput events_8_bins_cvgri --batch_size 4 \
                                   --exp_name "$exp_name"/"$run_descriptor" --logs_oled "$logs_docker_res" --training_mode test
          
          end_time=$(date +%s)

          # Copy local logs to system logs
          docker cp "$method_docker_id":${logs_docker_res} ${logs_res}

          echo time: "$((end_time-start_time))" > "$logs_time"
          echo "$data_eval_sys_path"
          echo size: "$(du -sh "$data_eval_sys_path")" > "$logs_size"

        done
      done
    done
  done
done
